"""Configuration du scraper CIH Bank — URLs extraites du sitemap.xml"""

import os

# --- Paramètres HTTP ---
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept-Language": "fr-FR,fr;q=0.9,ar;q=0.8",
}
REQUEST_DELAY = 1.5   # secondes entre chaque requête (politesse)
REQUEST_TIMEOUT = 15  # secondes avant abandon

# --- Chemins ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.join(BASE_DIR, "..")
RAW_DATA_DIR = os.path.join(PROJECT_DIR, "data", "raw")
CLEANED_DATA_DIR = os.path.join(PROJECT_DIR, "data", "cleaned")

# --- URLs par catégorie : (url, nom_fichier) ---
URLS = {
    "particuliers": [
        ("https://cihbank.ma/particuliers/devenir-client/code-60", "offre-code-60"),
        ("https://cihbank.ma/particuliers/devenir-client/code-18", "offre-code-18"),
        ("https://cihbank.ma/particuliers/devenir-client/Club-Sayidati", "club-sayidati"),
        ("https://cihbank.ma/particuliers/devenir-client/offre-fonctionnaires", "offre-fonctionnaires"),
        ("https://cihbank.ma/particuliers/devenir-client/Offres-Packages", "offres-packages"),
        ("https://cihbank.ma/particuliers/nos-offres/gerer-mes-comptes", "gerer-mes-comptes"),
        ("https://cihbank.ma/particuliers/nos-offres/financer-mes-projets", "financer-mes-projets"),
        ("https://cihbank.ma/particuliers/nos-offres/financer-mes-projets/credit-immobilier", "credit-immobilier"),
        ("https://cihbank.ma/particuliers/nos-offres/financer-mes-projets/credit-consommation", "credit-consommation"),
        ("https://cihbank.ma/particuliers/nos-offres/financer-mes-projets/credit-auto", "credit-auto"),
        ("https://cihbank.ma/particuliers/nos-offres/Epargner-et-Investir", "epargner-et-investir"),
        ("https://cihbank.ma/particuliers/nos-offres/Bancassurance-et-Assistance", "bancassurance-et-assistance"),
        ("https://cihbank.ma/particulier/nos-offres/cartes-bancaires", "cartes-bancaires"),
        ("https://cihbank.ma/particuliers/nos-offres/payer-factures-impots", "payer-factures-impots"),
        ("https://cihbank.ma/particuliers/nos-innovations/cih-mobile", "cih-mobile"),
        ("https://cihbank.ma/particuliers/nos-innovations/cih-online", "cih-online"),
        ("https://cihbank.ma/particuliers/nos-innovations/cih-express", "cih-express"),
        ("https://cihbank.ma/particuliers/nos-innovations/cih-geoassist", "cih-geoassist"),
        ("https://cihbank.ma/particuliers/nos-innovations/recuperation-IR", "recuperation-ir"),
        ("https://cihbank.ma/particuliers/nos-innovations/virement-real-time", "virement-real-time"),
        ("https://cihbank.ma/particuliers/nos-innovations/changement-agence", "changement-agence"),
        ("https://cihbank.ma/google-pay", "google-pay"),
        ("https://cihbank.ma/particulier/nos-offres/cartes-bancaires/cartes-multiservices/carte-saydati", "carte-saydati"),
        ("https://cihbank.ma/particulier/nos-offres/cartes-bancaires/cartes-multiservices/carte-visa-classic", "carte-visa-classic"),
        ("https://cihbank.ma/particulier/nos-offres/cartes-bancaires/cartes-multiservices/carte-go", "carte-go"),
        ("https://cihbank.ma/particulier/nos-offres/cartes-bancaires/cartes-multiservices/carte-visa-platinium", "carte-visa-platinium"),
        ("https://cihbank.ma/particulier/nos-offres/cartes-bancaires/cartes-multiservices/carte-code30", "carte-code30"),
        ("https://cihbank.ma/particulier/nos-offres/cartes-bancaires/cartes-multiservices/carte-mastercard-world-elite", "carte-mastercard-world-elite"),
        ("https://cihbank.ma/particulier/nos-offres/cartes-bancaires/cartes-multiservices/carte-code-gamer", "carte-code-gamer"),
        ("https://cihbank.ma/particulier/nos-offres/cartes-bancaires/cartes-multiservices/carte-visa-gold", "carte-visa-gold"),
        ("https://cihbank.ma/particulier/nos-offres/cartes-bancaires/cartes-multiservices/carte-code-60", "carte-code-60"),
        ("https://cihbank.ma/particulier/nos-offres/cartes-bancaires/cartes-internationales/carte-saphyr", "carte-saphyr"),
        ("https://cihbank.ma/particulier/nos-offres/cartes-bancaires/cartes-internationales/carte-saphyr-devises", "carte-saphyr-devises"),
        ("https://cihbank.ma/particulier/nos-offres/cartes-bancaires/cartes-multiservices/carte-mastercard-world-elite-devises", "carte-mastercard-world-elite-devises"),
        ("https://cihbank.ma/particulier/nos-offres/cartes-bancaires/cartes-prepayes/carte-almoussafir", "carte-almoussafir"),
        ("https://cihbank.ma/particulier/nos-offres/cartes-bancaires/cartes-prepayes/carte-binatna", "carte-binatna"),
        ("https://cihbank.ma/particulier/nos-offres/cartes-bancaires/cartes-prepayes/carte-eshopping", "carte-eshopping"),
        ("https://cihbank.ma/particulier/nos-offres/cartes-bancaires/cartes-prepayes/carte-ojour", "carte-ojour"),
        ("https://cihbank.ma/particuliers/nos-offres/Bancassurance-et-Assistance/Assurer-ma-famille", "assurer-ma-famille"),
    ],

    "professionnels": [
        ("https://cihbank.ma/Professionnels/devenir-client/Pack-ASSASS-Pro", "pack-assass-pro"),
        ("https://cihbank.ma/Professionnels/devenir-client/Pack-Raha-Pro", "pack-raha-pro"),
        ("https://cihbank.ma/Professionnels/devenir-client/Club-Saydati-Pro", "club-saydati-pro"),
        ("https://cihbank.ma/Professionnels/devenir-client/cih-sante-pro", "cih-sante-pro"),
        ("https://cihbank.ma/Professionnels/devenir-client/Code-Maalem", "code-maalem"),
        ("https://cihbank.ma/Professionnels/devenir-client/Offres-Packages", "offres-packages-pro"),
        ("https://cihbank.ma/Professionnels/nos-offres/Financement-investissement", "financement-investissement-pro"),
        ("https://cihbank.ma/Professionnels/nos-offres/Financement-exploitation", "financement-exploitation-pro"),
        ("https://cihbank.ma/Professionnels/nos-offres/Operations-international", "operations-international-pro"),
        ("https://cihbank.ma/Professionnels/nos-offres/Gestion-de-flux", "gestion-de-flux-pro"),
        ("https://cihbank.ma/Professionnels/nos-offres/Bancassurance", "bancassurance-pro"),
        ("https://cihbank.ma/Professionnels/nos-offres/Placement", "placement-pro"),
        ("https://cihbank.ma/Professionnels/nos-offres/cartes-bancaires", "cartes-bancaires-pro"),
        ("https://cihbank.ma/Professionnels/nos-innovations/cih-online-pro", "cih-online-pro"),
        ("https://cihbank.ma/Professionnels/nos-innovations/cih-mobile-pro", "cih-mobile-pro"),
        ("https://cihbank.ma/Professionnels/nos-innovations/Solution-E-cert", "solution-e-cert"),
        ("https://cihbank.ma/Professionnels/nos-innovations/cih-e-Trade", "cih-e-trade"),
        ("https://cihbank.ma/Professionnels/nos-innovations/cih-fx-trading", "cih-fx-trading"),
        ("https://cihbank.ma/Professionnels/nos-innovations/bourse-en-ligne", "bourse-en-ligne"),
        ("https://cihbank.ma/Professionnels/nos-innovations/Intelaw", "intelaw"),
        ("https://cihbank.ma/Professionnels/nos-offres/cartes-bancaires/cartes-multiservices/carte-visa-premier", "carte-visa-premier-pro"),
        ("https://cihbank.ma/Professionnels/nos-offres/cartes-bancaires/cartes-multiservices/Carte-Saydati-Pro", "carte-saydati-pro"),
        ("https://cihbank.ma/Professionnels/nos-offres/cartes-bancaires/cartes-multiservices/carte-Platinium-pro", "carte-platinium-pro"),
        ("https://cihbank.ma/Professionnels/nos-offres/cartes-bancaires/cartes-multiservices/carte-depovite", "carte-depovite"),
    ],

    "mdm": [
        ("https://cihbank.ma/MDM/devenir-client/offre_duo", "offre-duo"),
        ("https://cihbank.ma/MDM/devenir-client/offre_go", "offre-go"),
        ("https://cihbank.ma/MDM/devenir-client/code_212", "code-212"),
        ("https://cihbank.ma/MDM/devenir-client/Offres-Packages", "offres-packages-mdm"),
        ("https://cihbank.ma/MDM/nos-offres/Transfert-fonds-au-Maroc", "transfert-fonds"),
        ("https://cihbank.ma/MDM/nos-offres/financer-mes-projets", "financer-projets-mdm"),
        ("https://cihbank.ma/MDM/nos-offres/Epargner-et-Investir", "epargner-investir-mdm"),
        ("https://cihbank.ma/MDM/nos-offres/Bancassurance-et-Assistance", "bancassurance-mdm"),
        ("https://cihbank.ma/MDM/nos-offres/cartes-bancaires", "cartes-bancaires-mdm"),
        ("https://cihbank.ma/MDM/nos-innovations/cih-online", "cih-online-mdm"),
        ("https://cihbank.ma/MDM/nos-innovations/cih-mobile", "cih-mobile-mdm"),
        ("https://cihbank.ma/MDM/nos-offres/cartes-bancaires/cartes-multiservices/carte-go", "carte-go-mdm"),
        ("https://cihbank.ma/MDM/nos-offres/cartes-bancaires/cartes-multiservices/carte-saydati", "carte-saydati-mdm"),
        ("https://cihbank.ma/MDM/nos-offres/cartes-bancaires/cartes-multiservices/carte-code30", "carte-code30-mdm"),
        ("https://cihbank.ma/MDM/nos-offres/cartes-bancaires/cartes-multiservices/carte-visa-classic", "carte-visa-classic-mdm"),
        ("https://cihbank.ma/MDM/nos-offres/cartes-bancaires/cartes-multiservices/carte-visa-gold", "carte-visa-gold-mdm"),
        ("https://cihbank.ma/MDM/nos-offres/cartes-bancaires/cartes-multiservices/carte-visa-platinium", "carte-visa-platinium-mdm"),
        ("https://cihbank.ma/MDM/nos-offres/cartes-bancaires/cartes-multiservices/carte-mastercard-world-elite", "carte-world-elite-mdm"),
        ("https://cihbank.ma/MDM/nos-offres/cartes-bancaires/cartes-internationales/carte-saphyr", "carte-saphyr-mdm"),
        ("https://cihbank.ma/MDM/nos-offres/cartes-bancaires/cartes-internationales/carte-duo", "carte-duo-mdm"),
        ("https://cihbank.ma/MDM/nos-offres/cartes-bancaires/cartes-prepayes/carte-binatna", "carte-binatna-mdm"),
        ("https://cihbank.ma/MDM/nos-offres/cartes-bancaires/cartes-prepayes/carte-almoussafir", "carte-almoussafir-mdm"),
    ],

    "entreprises": [
        ("https://cihbank.ma/entreprise/", "entreprise-accueil"),
        ("https://cihbank.ma/entreprise/accueil", "entreprise-accueil-2"),
        ("https://cihbank.ma/entreprise/centres-affaires", "centres-affaires"),
        ("https://cihbank.ma/entreprise/Entreprises/Digital-Corporate", "digital-corporate"),
        ("https://cihbank.ma/entreprise/Entreprises/digital-corporate/cih-mobile-corpo", "cih-mobile-corpo"),
        ("https://cihbank.ma/entreprise/Entreprises/financement/Financement-investissement", "financement-investissement-ent"),
        ("https://cihbank.ma/entreprise/Entreprises/financement/Financement-exploitation", "financement-exploitation-ent"),
        ("https://cihbank.ma/entreprise/Entreprises/financement/Leasing-LLD", "leasing-lld"),
        ("https://cihbank.ma/entreprise/Entreprises/financement/Factoring", "factoring"),
        ("https://cihbank.ma/entreprise/Entreprises/financement/Couverture-sur-matieres-premieres", "couverture-matieres-premieres"),
        ("https://cihbank.ma/entreprise/Entreprises/trade-finance", "trade-finance"),
        ("https://cihbank.ma/entreprise/Entreprises/trade-finance/Instruments-reglements-import", "instruments-reglements-import"),
        ("https://cihbank.ma/entreprise/Entreprises/trade-finance/Instruments-financement-importations", "instruments-financement-import"),
        ("https://cihbank.ma/entreprise/Entreprises/trade-finance/Comptes-exportateurs", "comptes-exportateurs"),
        ("https://cihbank.ma/entreprise/Entreprises/trade-finance/Instruments-reglement-export", "instruments-reglement-export"),
        ("https://cihbank.ma/entreprise/Entreprises/trade-finance/Instruments-financement-export", "instruments-financement-export"),
        ("https://cihbank.ma/entreprise/Entreprises/trade-finance/Garanties-international", "garanties-international"),
        ("https://cihbank.ma/entreprise/Entreprises/trade-finance/Cautions-douanieres", "cautions-douanieres"),
        ("https://cihbank.ma/entreprise/Entreprises/trade-finance/Change", "change"),
        ("https://cihbank.ma/entreprise/Entreprises/Paiement-Cash-Management/Paiement", "paiement"),
        ("https://cihbank.ma/entreprise/Entreprises/Paiement-Cash-Management/Paiement/comptes-entreprises", "comptes-entreprises"),
        ("https://cihbank.ma/entreprise/Entreprises/Paiement-Cash-Management/Gestion-des-encaissements", "gestion-encaissements"),
        ("https://cihbank.ma/entreprise/Entreprises/Paiement-Cash-Management/Gestion-des-decaissements", "gestion-decaissements"),
        ("https://cihbank.ma/entreprise/Entreprises/Paiement-Cash-Management/Optimisation-tresorerie", "optimisation-tresorerie"),
        ("https://cihbank.ma/entreprise/Entreprises/Paiement-Cash-Management/Monetique", "monetique"),
        ("https://cihbank.ma/entreprise/Entreprises/Paiement-Cash-Management/Monetique/TPE", "tpe"),
        ("https://cihbank.ma/entreprise/Entreprises/Paiement-Cash-Management/Monetique/Guichet-Automatique-Bancaire", "gab"),
        ("https://cihbank.ma/entreprise/Entreprises/Paiement-Cash-Management/Monetique/Moyens-de-paiements", "moyens-de-paiements"),
        ("https://cihbank.ma/entreprise/Entreprises/Placements", "placements"),
        ("https://cihbank.ma/entreprise/Entreprises/Placements/Placement-classique", "placement-classique"),
        ("https://cihbank.ma/entreprise/Entreprises/Placements/Placement-sur-le-marche-monetaire", "placement-monetaire"),
        ("https://cihbank.ma/entreprise/Entreprises/Placements/Placement-sur-le-marche-des-capitaux", "placement-capitaux"),
        ("https://cihbank.ma/entreprise/Entreprises/Placements/Services", "services-placements"),
        ("https://cihbank.ma/entreprise/Entreprises/Paiement-Cash-Management/Monetique/Moyens-de-paiements/carte-visa-premier", "carte-visa-premier-ent"),
        ("https://cihbank.ma/entreprise/Entreprises/Paiement-Cash-Management/Monetique/Moyens-de-paiements/carte-visa-platinium-pro", "carte-visa-platinium-ent"),
        ("https://cihbank.ma/entreprise/Entreprises/Paiement-Cash-Management/Monetique/Moyens-de-paiements/carte-mastercard-world-elite", "carte-world-elite-ent"),
    ],

    "institutionnel": [
        ("https://cihbank.ma/Groupe-CIHBANK", "groupe-cih-bank"),
        ("https://cihbank.ma/espace-financier", "espace-financier"),
        ("https://cihbank.ma/actualites", "actualites"),
        ("https://cihbank.ma/etre-contacter", "contact"),
        ("https://cihbank.ma/communications", "communications"),
        ("https://cihbank.ma/conformite", "conformite"),
        ("https://cihbank.ma/developpement-durable", "developpement-durable"),
        ("https://cihbank.ma/notice-legale", "notice-legale"),
        ("https://cihbank.ma/tarification", "tarification"),
        ("https://cihbank.ma/politique-qualite", "politique-qualite"),
        ("https://cihbank.ma/usage-securise", "usage-securise"),
        ("https://cihbank.ma/nos-agences", "nos-agences"),
    ],
}

# --- PDFs à télécharger ---
PDF_URLS = [
    ("https://cihbank.ma/themes/ciht/pdf/mediation-bancaire.pdf", "mediation-bancaire"),
    ("https://cihbank.ma/themes/ciht/pdf/traitement-des-reclamations.pdf", "traitement-des-reclamations"),
    ("https://cihbank.ma/themes/ciht/pdf/ethique-deontologie.pdf", "ethique-deontologie"),
    ("https://cihbank.ma/themes/ciht/pdf/La%20politique_anti-corruption_CIH_Bank.pdf", "politique-anti-corruption"),
    ("https://cihbank.ma/entreprise/sites/default/files/Pdf/Guide-World-Elite.pdf", "guide-world-elite"),
]
